"""Curated quantum mechanics knowledge base: books, topics, curriculum graph."""
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Dict, List, Optional

LEVELS = ["basics", "intermediate", "advanced", "advanced_topics"]


@dataclass(frozen=True)
class Book:
    id: str
    title: str
    authors: str
    level: str
    topics: List[str]
    note: str
    why_read: str


@dataclass(frozen=True)
class Topic:
    id: str
    title: str
    level: str
    prerequisites: List[str]
    key_concepts: List[str]
    key_equations: List[str]
    intuition: str
    book_refs: List[str]
    problem_ids: List[str]


BOOKS: Dict[str, Book] = {b.id: b for b in [
    Book(
        id="feynman-vol3",
        title="The Feynman Lectures on Physics, Vol. III",
        authors="Richard P. Feynman, Robert B. Leighton, Matthew Sands",
        level="basics",
        topics=["wave-particle-duality", "double-slit", "uncertainty-principle"],
        note="Free online at feynmanlectures.caltech.edu",
        why_read="The best intuition-first introduction to QM ever written. Feynman explains quantum behavior from scratch with zero hand-waving.",
    ),
    Book(
        id="griffiths",
        title="Introduction to Quantum Mechanics",
        authors="David J. Griffiths",
        level="intermediate",
        topics=["schrodinger-equation", "particle-in-a-box", "harmonic-oscillator", "hydrogen-atom", "spin-pauli"],
        note="3rd edition (2018) recommended",
        why_read="The standard undergraduate text. Clear derivations, great problems, covers all core QM in one volume.",
    ),
    Book(
        id="shankar",
        title="Principles of Quantum Mechanics",
        authors="R. Shankar",
        level="intermediate",
        topics=["dirac-notation", "operators-observables", "harmonic-oscillator", "hydrogen-atom", "time-independent-perturbation"],
        note="2nd edition",
        why_read="Rigorous mathematical foundations with excellent Dirac notation treatment. Best bridge from undergrad to graduate QM.",
    ),
    Book(
        id="sakurai",
        title="Modern Quantum Mechanics",
        authors="J. J. Sakurai, Jim Napolitano",
        level="advanced",
        topics=["spin-pauli", "angular-momentum-addition", "time-independent-perturbation", "time-dependent-perturbation", "scattering-theory"],
        note="3rd edition (2020)",
        why_read="The graduate standard. Starts with spin rather than waves, develops formalism powerfully. Essential for PhD students.",
    ),
    Book(
        id="cohen-tannoudji",
        title="Quantum Mechanics (2 vols.)",
        authors="Claude Cohen-Tannoudji, Bernard Diu, Franck Laloë",
        level="advanced",
        topics=["operators-observables", "harmonic-oscillator", "angular-momentum-addition", "time-dependent-perturbation", "identical-particles"],
        note="Nobel Prize author",
        why_read="Encyclopedic coverage with detailed complements on every chapter. A comprehensive reference for the working physicist.",
    ),
    Book(
        id="dirac",
        title="The Principles of Quantum Mechanics",
        authors="Paul A. M. Dirac",
        level="advanced",
        topics=["dirac-notation", "operators-observables", "measurement-postulates", "relativistic-qm"],
        note="4th edition (1958), historically foundational",
        why_read="Dirac invented much of modern QM notation. Reading the original source builds deep appreciation for the formalism.",
    ),
    Book(
        id="zettili",
        title="Quantum Mechanics: Concepts and Applications",
        authors="Nouredine Zettili",
        level="intermediate",
        topics=["schrodinger-equation", "particle-in-a-box", "harmonic-oscillator", "hydrogen-atom", "spin-pauli"],
        note="2nd edition; contains many solved problems",
        why_read="Excellent problem-solving focus with fully worked examples. Great companion to Griffiths for building calculation skills.",
    ),
    Book(
        id="ballentine",
        title="Quantum Mechanics: A Modern Development",
        authors="Leslie E. Ballentine",
        level="advanced",
        topics=["measurement-postulates", "identical-particles", "scattering-theory", "decoherence"],
        note="Emphasizes the statistical (ensemble) interpretation",
        why_read="Provides the most rigorous and philosophically careful treatment of QM foundations and measurement theory.",
    ),
    Book(
        id="townsend",
        title="A Modern Approach to Quantum Mechanics",
        authors="John S. Townsend",
        level="intermediate",
        topics=["spin-pauli", "dirac-notation", "operators-observables", "angular-momentum-addition"],
        note="Starts with spin-½, like Sakurai but at undergrad level",
        why_read="Elegant spin-first approach that builds formalism early. Excellent for developing physical intuition alongside the math.",
    ),
    Book(
        id="weinberg-qm",
        title="Lectures on Quantum Mechanics",
        authors="Steven Weinberg",
        level="advanced",
        topics=["measurement-postulates", "time-independent-perturbation", "scattering-theory", "decoherence"],
        note="Reflects Weinberg's view on interpretations",
        why_read="A Nobel Laureate's perspective on QM fundamentals and what the formalism really means. Valuable for advanced students.",
    ),
    Book(
        id="landau-lifshitz-qm",
        title="Quantum Mechanics: Non-Relativistic Theory",
        authors="Lev D. Landau, Evgeny M. Lifshitz",
        level="advanced",
        topics=["schrodinger-equation", "harmonic-oscillator", "angular-momentum-addition", "wkb", "scattering-theory"],
        note="Course of Theoretical Physics Vol. 3",
        why_read="The Russian master class in theoretical physics. Dense but rewarding; every problem is a gem.",
    ),
    Book(
        id="nielsen-chuang",
        title="Quantum Computation and Quantum Information",
        authors="Michael A. Nielsen, Isaac L. Chuang",
        level="advanced_topics",
        topics=["quantum-information", "decoherence"],
        note="'Mike and Ike' — the bible of QC",
        why_read="The definitive textbook on quantum computing and information theory. Essential for anyone working in quantum technology.",
    ),
    Book(
        id="feynman-hibbs",
        title="Quantum Mechanics and Path Integrals",
        authors="Richard P. Feynman, Albert R. Hibbs",
        level="advanced_topics",
        topics=["path-integrals"],
        note="Emended edition by Styer (2010)",
        why_read="Feynman's own development of path integrals — a completely different and beautiful way to think about quantum amplitudes.",
    ),

    # ─── FOUNDATIONS & FIRST EXPOSURE ───────────────────────────────────────
    Book(
        id="susskind-tm",
        title="Quantum Mechanics: The Theoretical Minimum",
        authors="Leonard Susskind, Art Friedman",
        level="basics",
        topics=["dirac-notation", "operators-observables", "measurement-postulates", "spin-pauli"],
        note="Companion to the Stanford lecture series",
        why_read="Starts from spin rather than waves, so the linear algebra that IS quantum mechanics arrives before any differential equation. The fastest honest route to bra-ket notation.",
    ),
    Book(
        id="fleisch-schrodinger",
        title="A Student's Guide to the Schrödinger Equation",
        authors="Daniel A. Fleisch",
        level="basics",
        topics=["schrodinger-equation", "wavefunction-born-rule", "particle-in-a-box"],
        note="",
        why_read="Walks the equation term by term, symbol by symbol. If the Schrödinger equation still looks like a wall of notation, this is the book that dismantles it.",
    ),
    Book(
        id="zubairy-beginners",
        title="Quantum Mechanics for Beginners: with Applications to Quantum Communication and Quantum Computing",
        authors="M. Suhail Zubairy",
        level="basics",
        topics=["wave-particle-duality", "double-slit", "measurement-postulates", "quantum-information"],
        note="",
        why_read="Reaches entanglement and quantum cryptography with almost no formalism, which makes it unusually good at showing WHY the postulates matter before you can manipulate them.",
    ),
    Book(
        id="piccirillo-maths-physics",
        title="Introduction to the Maths and Physics of Quantum Mechanics",
        authors="Lucio Piccirillo",
        level="basics",
        topics=["schrodinger-equation", "operators-observables", "wavefunction-born-rule"],
        note="",
        why_read="Builds the mathematics you need alongside the physics that needs it, instead of assuming a methods course you may not have taken.",
    ),
    Book(
        id="verstraete-nobody",
        title="Why Nobody Understands Quantum Physics",
        authors="Frank Verstraete, Céline Broeckaert",
        level="basics",
        topics=["wave-particle-duality", "measurement-postulates", "decoherence"],
        note="Popular-level, written by a working quantum information theorist",
        why_read="An honest account of what is genuinely unresolved versus what merely sounds strange — useful early, because it stops you mistaking your own confusion for the theory's.",
    ),
    Book(
        id="simply-quantum",
        title="Simply Quantum Physics",
        authors="DK (Miezan van Zyl, ed.)",
        level="basics",
        topics=["wave-particle-duality", "photoelectric-effect", "bohr-model", "uncertainty-principle"],
        note="Illustrated reference",
        why_read="One idea per page with a diagram. Not a course, but a fast way to place an unfamiliar term before reading a real treatment of it.",
    ),
    Book(
        id="house-fundamentals",
        title="Fundamentals of Quantum Mechanics",
        authors="James E. House",
        level="basics",
        topics=["schrodinger-equation", "particle-in-a-box", "harmonic-oscillator", "hydrogen-atom"],
        note="Written for chemists",
        why_read="Solves the standard model problems with the applications a chemist actually needs, and skips the formal apparatus. Good if you want results before machinery.",
    ),
    Book(
        id="brody-joy-qc",
        title="The Joy of Quantum Computing: A Concise Introduction",
        authors="Jed Brody",
        level="basics",
        topics=["quantum-information", "measurement-postulates"],
        note="",
        why_read="Gets to Bell inequalities and simple algorithms with minimal prerequisites — a gentler on-ramp than Nielsen & Chuang.",
    ),

    # ─── CORE COURSE TEXTS ──────────────────────────────────────────────────
    Book(
        id="zwiebach-mastering",
        title="Mastering Quantum Mechanics: Essentials, Theory, and Applications",
        authors="Barton Zwiebach",
        level="intermediate",
        topics=["dirac-notation", "operators-observables", "harmonic-oscillator", "spin-pauli", "angular-momentum-addition"],
        note="Grew out of MIT 8.05-8.06",
        why_read="Exceptionally careful with the linear algebra most books rush. If a step in an operator argument feels like sleight of hand elsewhere, Zwiebach has almost certainly spelled it out.",
    ),
    Book(
        id="mcintyre-paradigms",
        title="Quantum Mechanics: A Paradigms Approach",
        authors="David H. McIntyre",
        level="intermediate",
        topics=["spin-pauli", "dirac-notation", "measurement-postulates", "operators-observables"],
        note="Spin-first ordering",
        why_read="Opens with Stern-Gerlach and stays in finite-dimensional spaces for a long time, so measurement and superposition are concrete before wavefunctions appear.",
    ),
    Book(
        id="tamvakis-basic",
        title="Basic Quantum Mechanics",
        authors="Kyriakos Tamvakis",
        level="intermediate",
        topics=["schrodinger-equation", "harmonic-oscillator", "hydrogen-atom", "time-independent-perturbation"],
        note="",
        why_read="A compact one-semester treatment with worked problems throughout — closer to a lecture course in print than an encyclopedia.",
    ),
    Book(
        id="cejnar-condensed",
        title="A Condensed Course of Quantum Mechanics",
        authors="Pavel Cejnar",
        level="intermediate",
        topics=["operators-observables", "measurement-postulates", "density-matrix", "identical-particles"],
        note="Second edition",
        why_read="Dense and structural. Best read as a map of how the pieces fit once you have met them, not as first exposure.",
    ),
    Book(
        id="kumar-fundamentals",
        title="Fundamentals of Quantum Mechanics",
        authors="Ajit Kumar",
        level="intermediate",
        topics=["schrodinger-equation", "operators-observables", "harmonic-oscillator", "hydrogen-atom"],
        note="",
        why_read="Standard syllabus coverage with a steady, worked pace — a reliable second text when Griffiths moves too quickly on a topic.",
    ),
    Book(
        id="rajasekar-i",
        title="Quantum Mechanics I: The Fundamentals",
        authors="S. Rajasekar, R. Velusamy",
        level="intermediate",
        topics=["schrodinger-equation", "particle-in-a-box", "harmonic-oscillator", "hydrogen-atom", "operators-observables"],
        note="Volume I of two",
        why_read="Unusually explicit about solution methods, with numerical treatments alongside the analytic ones.",
    ),
    Book(
        id="everitt-qm",
        title="Quantum Mechanics",
        authors="Mark Julian Everitt",
        level="intermediate",
        topics=["dirac-notation", "operators-observables", "density-matrix", "decoherence"],
        note="",
        why_read="Modern in emphasis: open systems and density matrices arrive early rather than as an advanced afterthought.",
    ),
    Book(
        id="larkoski-math-intro",
        title="Quantum Mechanics: A Mathematical Introduction",
        authors="Andrew J. Larkoski",
        level="intermediate",
        topics=["dirac-notation", "operators-observables", "commutators", "schrodinger-heisenberg-pictures"],
        note="",
        why_read="Takes the mathematical structure as the subject rather than the scaffolding, while staying readable — a bridge toward von Neumann.",
    ),
    Book(
        id="burkhardt-foundations",
        title="Foundations of Quantum Physics",
        authors="Charles E. Burkhardt, Jacob J. Leventhal",
        level="intermediate",
        topics=["hydrogen-atom", "angular-momentum-addition", "spin-pauli", "time-independent-perturbation"],
        note="",
        why_read="Strong on atomic structure and angular momentum coupling — the part of the course where most texts get terse.",
    ),
    Book(
        id="papp-mastering",
        title="Mastering Quantum Mechanics",
        authors="Zoltán Papp",
        level="intermediate",
        topics=["schrodinger-equation", "scattering-theory", "operators-observables"],
        note="",
        why_read="Problem-led, with scattering treated as a first-class topic rather than a final chapter.",
    ),
    Book(
        id="konishi-new-intro",
        title="Quantum Mechanics: A New Introduction",
        authors="Kenichi Konishi, Giampiero Paffuti",
        level="intermediate",
        topics=["schrodinger-equation", "operators-observables", "identical-particles", "density-matrix"],
        note="",
        why_read="Covers the standard syllabus but keeps returning to interpretation and entanglement, which most course texts postpone indefinitely.",
    ),

    # ─── PROBLEM BOOKS ──────────────────────────────────────────────────────
    Book(
        id="cahay-problem-solving",
        title="Problem Solving in Quantum Mechanics: From Basics to Real-World Applications",
        authors="Marc Cahay, Supriyo Bandyopadhyay",
        level="intermediate",
        topics=["step-barrier-tunneling", "finite-well", "particle-in-a-box", "density-matrix"],
        note="Aimed at materials scientists and applied physicists",
        why_read="Problems drawn from devices rather than idealisations — tunnelling and confinement as they appear in real structures.",
    ),
    Book(
        id="cini-solved-problems",
        title="Solved Problems in Quantum and Statistical Mechanics",
        authors="Michele Cini, Francesco Fucito, Mauro Sbragaglia",
        level="intermediate",
        topics=["harmonic-oscillator", "time-independent-perturbation", "quantum-statistical-mechanics", "identical-particles"],
        note="Fully worked solutions",
        why_read="Worked in full, including the steps textbooks leave to the reader. Use it after attempting a problem, not instead.",
    ),

    # ─── ADVANCED & MATHEMATICAL ────────────────────────────────────────────
    Book(
        id="von-neumann-foundations",
        title="Mathematical Foundations of Quantum Mechanics",
        authors="John von Neumann",
        level="advanced",
        topics=["measurement-postulates", "operators-observables", "density-matrix"],
        note="1932; the origin of the Hilbert-space formulation",
        why_read="Where the density matrix and the projection postulate come from. Historically decisive and still the cleanest statement of what a measurement is taken to be.",
    ),
    Book(
        id="teta-math-primer",
        title="A Mathematical Primer on Quantum Mechanics",
        authors="Alessandro Teta",
        level="advanced",
        topics=["operators-observables", "schrodinger-equation", "measurement-postulates"],
        note="",
        why_read="Makes the functional analysis explicit — self-adjointness, domains, spectra — that physics texts wave through. Read it when 'Hermitian' stops feeling sufficient.",
    ),
    Book(
        id="beyer-intro",
        title="Introduction to Quantum Mechanics",
        authors="Horst R. Beyer",
        level="advanced",
        topics=["operators-observables", "schrodinger-equation", "commutators"],
        note="Mathematically rigorous",
        why_read="A rigorous development for readers who want the theorems rather than the physicist's shorthand.",
    ),
    Book(
        id="cecotti-exact-methods",
        title="Quantum Mechanics: A Concise Textbook with Emphasis on Exact Methods",
        authors="Sergio Cecotti",
        level="advanced",
        topics=["harmonic-oscillator", "hydrogen-atom", "wkb", "path-integrals"],
        note="",
        why_read="Concentrates on what can be solved exactly and why, which is a sharper lens on the structure than another survey of approximations.",
    ),
    Book(
        id="mahan-nutshell",
        title="Quantum Mechanics in a Nutshell",
        authors="Gerald D. Mahan",
        level="advanced",
        topics=["time-independent-perturbation", "scattering-theory", "second-quantization", "identical-particles"],
        note="",
        why_read="Graduate coverage at pace, with condensed-matter applications a pure-theory text would omit.",
    ),
    Book(
        id="landau-second-course",
        title="Quantum Mechanics: A Second Course in Quantum Theory",
        authors="Rubin H. Landau",
        level="advanced",
        topics=["scattering-theory", "relativistic-qm", "identical-particles", "time-dependent-perturbation"],
        note="Computational emphasis",
        why_read="Picks up where a first course stops and computes — genuinely useful if you want to implement rather than only derive.",
    ),
    Book(
        id="cetto-physical-approach",
        title="Quantum Mechanics: A Physical Approach",
        authors="Ana María Cetto, Luis de la Peña",
        level="advanced",
        topics=["measurement-postulates", "wavefunction-born-rule", "decoherence"],
        note="Emphasises physical interpretation over formalism",
        why_read="Argues for reading the formalism physically rather than instrumentally. A dissenting voice worth hearing once the standard account is secure.",
    ),
    Book(
        id="rajasekar-ii",
        title="Quantum Mechanics II: Advanced Topics",
        authors="S. Rajasekar, R. Velusamy",
        level="advanced_topics",
        topics=["path-integrals", "relativistic-qm", "quantum-information", "decoherence"],
        note="Second edition; volume II of two",
        why_read="A survey of where quantum mechanics went after the standard course — path integrals, relativistic wave equations, information, and open systems in one place.",
    ),

    # ─── QUANTUM FIELD THEORY ───────────────────────────────────────────────
    Book(
        id="lancaster-blundell",
        title="Quantum Field Theory for the Gifted Amateur",
        authors="Tom Lancaster, Stephen J. Blundell",
        level="advanced_topics",
        topics=["qft-fundamentals", "second-quantization", "path-integrals"],
        note="",
        why_read="The kindest genuine introduction to QFT in print: very short chapters, each doing one thing, with the motivation stated before the machinery.",
    ),
    Book(
        id="strickland-rqft",
        title="Relativistic Quantum Field Theory",
        authors="Michael Strickland",
        level="advanced_topics",
        topics=["qft-fundamentals", "relativistic-qm", "second-quantization"],
        note="",
        why_read="A compact, modern route from the relativistic wave equations to quantised fields.",
    ),
    Book(
        id="taylor-first-qft",
        title="A First Graduate Course in Quantum Field Theory",
        authors="Travis S. Taylor",
        level="advanced_topics",
        topics=["qft-fundamentals", "second-quantization"],
        note="",
        why_read="Paced for a first graduate encounter, with the calculational steps kept visible.",
    ),
    Book(
        id="salasnich-many-body",
        title="Quantum Many-Body Physics: A Path Integral Approach",
        authors="Luca Salasnich",
        level="advanced_topics",
        topics=["path-integrals", "second-quantization", "quantum-statistical-mechanics", "identical-particles"],
        note="",
        why_read="Connects path integrals to many-body statistical physics — the natural sequel once single-particle quantum mechanics is comfortable.",
    ),

    # ─── QUANTUM OPTICS & PHOTONICS ─────────────────────────────────────────
    Book(
        id="haroche-raimond",
        title="Exploring the Quantum: Atoms, Cavities, and Photons",
        authors="Serge Haroche, Jean-Michel Raimond",
        level="advanced_topics",
        topics=["quantum-optics", "decoherence", "measurement-postulates"],
        note="Haroche shared the 2012 Nobel Prize for this work",
        why_read="Decoherence as something measured in a laboratory rather than argued about. The best available account of watching a superposition die.",
    ),
    Book(
        id="grynberg-quantum-optics",
        title="Introduction to Quantum Optics: From the Semi-classical Approach to Quantized Light",
        authors="Gilbert Grynberg, Alain Aspect, Claude Fabre",
        level="advanced_topics",
        topics=["quantum-optics", "time-dependent-perturbation", "second-quantization"],
        note="",
        why_read="Builds from semi-classical light-matter interaction to full field quantisation, so you see exactly which results need a quantised field and which do not.",
    ),
    Book(
        id="cohen-tannoudji-atom-photon",
        title="Atom-Photon Interactions: Basic Processes and Applications",
        authors="Claude Cohen-Tannoudji, Jacques Dupont-Roc, Gilbert Grynberg",
        level="advanced_topics",
        topics=["quantum-optics", "time-dependent-perturbation", "second-quantization"],
        note="",
        why_read="The reference for atom-field interaction, from a Nobel laureate in laser cooling. Dense, and the standard against which lighter treatments are judged.",
    ),
    Book(
        id="rice-quantum-optics",
        title="An Introduction to Quantum Optics",
        authors="Perry Rice",
        level="advanced_topics",
        topics=["quantum-optics", "density-matrix"],
        note="Second edition",
        why_read="A shorter entry point to quantum optics that still reaches cavity QED and photon statistics.",
    ),
    Book(
        id="saleh-quantum-photonics",
        title="Quantum Photonics: Bimodes, Qubits, and Biphotons",
        authors="Bahaa E. A. Saleh",
        level="advanced_topics",
        topics=["quantum-optics", "quantum-information"],
        note="2025",
        why_read="Photonic qubits and biphoton states from the author of the standard photonics text — where quantum optics meets practical quantum technology.",
    ),
    Book(
        id="thyagarajan-integrated-photonics",
        title="Integrated Quantum Photonics",
        authors="Krishna Thyagarajan",
        level="advanced_topics",
        topics=["quantum-optics", "quantum-information"],
        note="",
        why_read="How photonic quantum devices are actually built on a chip — the engineering constraints that theory papers omit.",
    ),
    Book(
        id="byrnes-atom-optics",
        title="Quantum Atom Optics: Theory and Applications to Quantum Technology",
        authors="Tim Byrnes, Ebubechukwu O. Ilo-Okeke",
        level="advanced_topics",
        topics=["quantum-optics", "identical-particles", "quantum-information"],
        note="",
        why_read="Cold atoms and condensates as a quantum technology platform, with the many-body theory kept alongside the applications.",
    ),

    # ─── FOUNDATIONS, INFORMATION & INTERPRETATION ──────────────────────────
    Book(
        id="bertlmann-friis",
        title="Modern Quantum Theory: From Quantum Mechanics to Entanglement and Quantum Information",
        authors="Reinhold A. Bertlmann, Nicolai Friis",
        level="advanced_topics",
        topics=["quantum-information", "decoherence", "measurement-postulates", "density-matrix"],
        note="",
        why_read="Takes entanglement and Bell inequalities as the centre of the subject rather than a closing curiosity. Bertlmann's socks, from the man himself.",
    ),
    Book(
        id="valentini-beyond",
        title="Beyond the Quantum: A Quest for the Origin and Hidden Meaning of Quantum Mechanics",
        authors="Antony Valentini",
        level="advanced_topics",
        topics=["measurement-postulates", "decoherence", "wavefunction-born-rule"],
        note="Argues from the pilot-wave (de Broglie-Bohm) programme",
        why_read="A serious case that the Born rule is a contingent equilibrium rather than a law. Read it to see which of your assumptions are physics and which are convention.",
    ),
    Book(
        id="bacciagaluppi-einstein-paradox",
        title="The Einstein Paradox: The Debate on Nonlocality and Incompleteness in 1935",
        authors="Guido Bacciagaluppi, Elise Crull",
        level="advanced_topics",
        topics=["measurement-postulates", "quantum-information"],
        note="Historical, with primary sources",
        why_read="What EPR actually said, and what Bohr actually replied, rather than the textbook summary of both.",
    ),
    Book(
        id="shapira-algorithms",
        title="Quantum Mechanics and Algorithms: An Algebraic-Geometric Perspective",
        authors="Yair Shapira",
        level="advanced_topics",
        topics=["quantum-information", "operators-observables"],
        note="",
        why_read="Approaches quantum algorithms through the underlying algebra and geometry rather than circuit diagrams.",
    ),
    Book(
        id="babar-classical-to-quantum-coding",
        title="From Classical to Quantum Coding",
        authors="Zunaira Babar, Daryus Chandra, Soon Xin Ng, Lajos Hanzo",
        level="advanced_topics",
        topics=["quantum-information", "decoherence"],
        note="",
        why_read="Quantum error correction developed from classical coding theory, which is the way to understand it if you already know the classical side.",
    ),
    Book(
        id="ramkarthik-numerical-qi",
        title="Numerical Recipes in Quantum Information Theory and Quantum Computing",
        authors="M. S. Ramkarthik, Payal D. Solanki",
        level="advanced_topics",
        topics=["quantum-information", "density-matrix"],
        note="Worked implementations in FORTRAN 90",
        why_read="Actual code for entanglement measures and state manipulation — the gap between a formula and a working computation is where most understanding is lost.",
    ),
    Book(
        id="zhou-teleportation",
        title="Design of Quantum Teleportation Schemes",
        authors="Ri-Gui Zhou, Xiao-Xue Zhang, Lin-Tao Du",
        level="advanced_topics",
        topics=["quantum-information"],
        note="Monograph",
        why_read="A narrow, deep treatment of teleportation protocols — useful once the textbook version no longer raises questions.",
    ),
    Book(
        id="hartle-quantum-universe",
        title="The Quantum Universe: Essays on Quantum Mechanics, Quantum Cosmology, and Physics in General",
        authors="James B. Hartle",
        level="advanced_topics",
        topics=["cosmology", "measurement-postulates", "decoherence"],
        note="Collected essays",
        why_read="What it means to apply quantum mechanics to a universe with no external observer — the decoherent-histories programme from one of its architects.",
    ),
    Book(
        id="fantoni-unifying",
        title="Unifying Classical and Quantum Physics",
        authors="Riccardo Fantoni",
        level="advanced_topics",
        topics=["measurement-postulates", "path-integrals", "decoherence"],
        note="",
        why_read="An attempt at a single framework spanning both regimes. Speculative in places; read it as an argument, not a textbook.",
    ),
    Book(
        id="bruzzaniti-visible-invisible",
        title="Of Things Visible and Invisible: From the Atom to Quarks",
        authors="Giuseppe Bruzzaniti",
        level="advanced_topics",
        topics=["standard-model", "qft-fundamentals"],
        note="History of physics",
        why_read="How the picture of matter was actually assembled, mistake by mistake. Useful context for why the Standard Model is shaped the way it is.",
    ),
    Book(
        id="vega-quantum-electronics",
        title="Quantum Electronics: Theory, Technologies and Applications",
        authors="Diego Vega Ramirez",
        level="advanced_topics",
        topics=["quantum-optics", "step-barrier-tunneling"],
        note="Master in Electronics series, Book 7",
        why_read="The engineering end: lasers, tunnelling devices and quantum electronics as built objects.",
    ),
]}

TOPICS: Dict[str, Topic] = {t.id: t for t in [
    # ─── BASICS ──────────────────────────────────────────────────────────────
    Topic(
        id="newtons-laws-of-motion",
        title="Newton's Laws of Motion",
        level="basics",
        prerequisites=[],
        key_concepts=["Newton's second law", "net force", "proportional acceleration",
                     "kinematic motion equations", "work-energy theorem",
                     "gravitational potential energy converts to kinetic energy",
                     "speed after falling from rest", "gravitational free fall"],
        key_equations=[r"F = ma", r"v^2 = v_0^2 + 2a\,\Delta x", r"KE = \tfrac{1}{2}mv^2",
                      r"PE = mgh", r"\tfrac{1}{2}mv^2 = mgh"],
        intuition="A net force produces an acceleration in exact proportion to it (F=ma), "
                 "and free of friction or air resistance, an object's gravitational potential "
                 "energy converts completely into kinetic energy as it falls, so its final "
                 "speed follows from the height it fell, not its mass. These are the "
                 "elementary tools every more sophisticated formalism has to reduce to in the "
                 "appropriate limit.",
        book_refs=[],
        problem_ids=[],
    ),
    Topic(
        id="lagrangian-hamiltonian-mechanics",
        title="Lagrangian and Hamiltonian Mechanics",
        level="basics",
        prerequisites=[],
        key_concepts=["generalized coordinates", "the principle of least action", "Euler-Lagrange equation", "Legendre transform to the Hamiltonian", "Hamilton's equations", "phase space", "canonical momentum", "cyclic coordinates and conserved quantities"],
        key_equations=[r"L = T - V", r"\frac{d}{dt}\frac{\partial L}{\partial \dot{q}_i} - \frac{\partial L}{\partial q_i} = 0", r"H(q,p) = \sum_i p_i \dot{q}_i - L", r"\dot{q}_i = \frac{\partial H}{\partial p_i},\ \dot{p}_i = -\frac{\partial H}{\partial q_i}"],
        intuition="Newton's F=ma works in Cartesian coordinates, but real systems are easier to describe with generalized coordinates — an angle, an arc length, whatever is natural for the constraint. The Lagrangian L=T-V turns 'find the equations of motion' into 'find the path that extremizes the action.' The Hamiltonian, built from L by a Legendre transform, rephrases the same dynamics again as two first-order equations in position and momentum evolving together in phase space — the classical mechanics that quantum mechanics itself grew out of, with the Hamiltonian carrying over directly as the generator of time evolution.",
        book_refs=[],
        problem_ids=[],
    ),
    Topic(
        id="wave-particle-duality",
        title="Wave–Particle Duality",
        level="basics",
        prerequisites=[],
        key_concepts=["photons behave as both wave and particle", "matter has wave properties", "complementarity principle"],
        key_equations=[r"E = h\nu", r"\lambda = h/p"],
        intuition="Light is neither a pure wave nor a pure particle — it is something new that shows wave behavior in some experiments and particle behavior in others. The question 'which is it?' is the wrong question.",
        book_refs=["feynman-vol3", "griffiths"],
        problem_ids=[],  # derived from problems.py at serialization,
    ),
    Topic(
        id="photoelectric-effect",
        title="The Photoelectric Effect",
        level="basics",
        prerequisites=["wave-particle-duality"],
        key_concepts=["photon energy quantization", "work function", "threshold frequency", "Einstein's 1905 explanation"],
        key_equations=[r"E_{\text{photon}} = h\nu", r"KE_{\max} = h\nu - \phi"],
        intuition="Shining light on metal ejects electrons only if the frequency is high enough — not the intensity. Einstein realized light must come in discrete packets (photons) each with energy hν.",
        book_refs=["feynman-vol3", "griffiths"],
        problem_ids=[],  # derived from problems.py at serialization,
    ),
    Topic(
        id="de-broglie",
        title="de Broglie Wavelength",
        level="basics",
        prerequisites=["wave-particle-duality"],
        key_concepts=["matter waves", "de Broglie relation", "wave vector k", "electron diffraction"],
        key_equations=[r"\lambda = \frac{h}{p}", r"k = \frac{p}{\hbar} = \frac{2\pi}{\lambda}"],
        intuition="Just as Einstein showed light has momentum p = E/c = h/λ, de Broglie reversed it: particles with momentum p have an associated wavelength λ = h/p. Electrons really do diffract like waves.",
        book_refs=["feynman-vol3", "griffiths", "zettili"],
        problem_ids=[],  # derived from problems.py at serialization,
    ),
    Topic(
        id="double-slit",
        title="The Double-Slit Experiment",
        level="basics",
        prerequisites=["wave-particle-duality", "de-broglie"],
        key_concepts=["interference of probability amplitudes", "which-path information destroys interference", "quantum measurement affects the system"],
        key_equations=[r"P_{12} = |A_1 + A_2|^2 \neq P_1 + P_2"],
        intuition="When you don't know which slit the electron went through, its probability amplitudes interfere. The moment you measure which path, interference disappears. This is the central mystery of quantum mechanics.",
        book_refs=["feynman-vol3"],
        problem_ids=[],
    ),
    Topic(
        id="blackbody-radiation",
        title="Blackbody Radiation & Planck's Law",
        level="basics",
        prerequisites=[],
        key_concepts=["ultraviolet catastrophe", "energy quantization", "Planck constant", "Stefan-Boltzmann law"],
        key_equations=[r"E_n = n h\nu", r"u(\nu,T) = \frac{8\pi h\nu^3}{c^3} \frac{1}{e^{h\nu/k_B T}-1}"],
        intuition="Classical physics predicted infinite energy at high frequencies (the UV catastrophe). Planck's radical fix: energy is only exchanged in discrete chunks E = nhν. This was the birth of quantum theory.",
        book_refs=["griffiths", "zettili"],
        problem_ids=[],
    ),
    Topic(
        id="bohr-model",
        title="The Bohr Model of the Atom",
        level="basics",
        prerequisites=["photoelectric-effect", "de-broglie"],
        key_concepts=["quantized orbits", "energy levels", "emission and absorption spectra", "Rydberg formula", "Balmer series transition wavelengths"],
        key_equations=[r"E_n = -\frac{13.6\,\text{eV}}{n^2}", r"\frac{1}{\lambda} = R_\infty\!\left(\frac{1}{n_f^2} - \frac{1}{n_i^2}\right)"],
        intuition="Bohr postulated that electrons only occupy orbits where their de Broglie wave fits exactly around the circle. This explains hydrogen's spectral lines but fails for multi-electron atoms.",
        book_refs=["griffiths", "zettili", "feynman-vol3"],
        problem_ids=[],  # derived from problems.py at serialization,
    ),
    Topic(
        id="uncertainty-principle",
        title="Heisenberg Uncertainty Principle",
        level="basics",
        prerequisites=["wave-particle-duality", "de-broglie"],
        key_concepts=["position-momentum uncertainty", "energy-time uncertainty", "not an experimental limitation but fundamental", "uncertainty in position and momentum measurements", "minimum uncertainty product"],
        key_equations=[r"\Delta x \,\Delta p \geq \frac{\hbar}{2}", r"\Delta E \,\Delta t \geq \frac{\hbar}{2}"],
        intuition="To know where a particle is precisely, you need a narrow wave packet — but a narrow packet requires many wavelengths, meaning many momenta. Localizing position unavoidably spreads momentum. This is geometry, not ignorance.",
        book_refs=["feynman-vol3", "griffiths", "shankar"],
        problem_ids=[],  # derived from problems.py at serialization,
    ),
    Topic(
        id="wavefunction-born-rule",
        title="The Wavefunction and Born Rule",
        level="basics",
        prerequisites=["wave-particle-duality", "double-slit"],
        key_concepts=["wavefunction ψ(x,t)", "probability density |ψ|²", "normalization", "superposition principle"],
        key_equations=[r"P(x) = |\psi(x,t)|^2", r"\int_{-\infty}^{\infty}|\psi|^2 \,dx = 1"],
        intuition="The wavefunction is a complex probability amplitude. Its squared magnitude gives the probability of finding the particle at a location. Before measurement the particle is in a superposition; measurement 'collapses' the wavefunction.",
        book_refs=["griffiths", "feynman-vol3", "shankar"],
        problem_ids=[],
    ),
    Topic(
        id="schrodinger-equation",
        title="The Schrödinger Equation",
        level="basics",
        prerequisites=["wavefunction-born-rule", "de-broglie"],
        key_concepts=["time-dependent Schrödinger equation", "time-independent form", "stationary states", "energy eigenvalues"],
        key_equations=[
            r"i\hbar\frac{\partial\psi}{\partial t} = \hat{H}\psi",
            r"-\frac{\hbar^2}{2m}\frac{d^2\psi}{dx^2} + V\psi = E\psi",
        ],
        intuition="Schrödinger's equation is the quantum version of F=ma. It tells us how the wavefunction evolves in time. For stationary states with definite energy, it reduces to a spatial eigenvalue equation.",
        book_refs=["griffiths", "shankar", "zettili"],
        problem_ids=[],
    ),
    Topic(
        id="particle-in-a-box",
        title="Infinite Square Well (Particle in a Box)",
        level="basics",
        prerequisites=["schrodinger-equation", "wavefunction-born-rule"],
        key_concepts=["boundary conditions", "quantized energies", "standing waves", "zero-point energy"],
        key_equations=[
            r"E_n = \frac{n^2\pi^2\hbar^2}{2mL^2}",
            r"\psi_n(x) = \sqrt{\frac{2}{L}}\sin\!\left(\frac{n\pi x}{L}\right)",
        ],
        intuition="Confine a particle between two walls. Only standing-wave solutions fit — exactly like a guitar string. The energy is quantized as n², and even the ground state (n=1) has non-zero energy: the zero-point energy.",
        book_refs=["griffiths", "shankar", "zettili", "feynman-vol3"],
        problem_ids=[],  # derived from problems.py at serialization,
    ),
    # ─── INTERMEDIATE ─────────────────────────────────────────────────────────
    Topic(
        id="step-barrier-tunneling",
        title="Potential Step, Barrier & Quantum Tunneling",
        level="intermediate",
        prerequisites=["particle-in-a-box", "schrodinger-equation"],
        key_concepts=["reflection and transmission coefficients", "evanescent wave", "tunneling through classically forbidden region", "WKB tunneling rate"],
        key_equations=[
            r"T \approx e^{-2\kappa L},\quad \kappa = \sqrt{2m(V_0-E)}/\hbar",
        ],
        intuition="Classically, a ball with less energy than a hill cannot cross. Quantum mechanically, the wavefunction decays exponentially inside the barrier but doesn't vanish — there's a non-zero probability of appearing on the other side. Tunnel diodes and nuclear fusion rely on this.",
        book_refs=["griffiths", "shankar", "zettili"],
        problem_ids=[],  # derived from problems.py at serialization,
    ),
    Topic(
        id="finite-well",
        title="Finite Square Well",
        level="intermediate",
        prerequisites=["particle-in-a-box", "step-barrier-tunneling"],
        key_concepts=["bound states", "tunneling into classically forbidden region", "transcendental equations for eigenvalues"],
        key_equations=[r"k\tan(ka) = \kappa,\quad k = \sqrt{2mE}/\hbar,\quad \kappa = \sqrt{2m(V_0-E)}/\hbar"],
        intuition="A finite well has fewer bound states than the infinite well, and they're slightly lower in energy. The wavefunction leaks outside the well — the particle can 'be found' in classically forbidden regions.",
        book_refs=["griffiths", "shankar"],
        problem_ids=[],
    ),
    Topic(
        id="harmonic-oscillator",
        title="Quantum Harmonic Oscillator",
        level="intermediate",
        prerequisites=["schrodinger-equation", "particle-in-a-box"],
        key_concepts=["ladder operators (creation and annihilation)", "equally-spaced energy levels", "zero-point energy", "coherent states"],
        key_equations=[
            r"E_n = \hbar\omega\!\left(n + \tfrac{1}{2}\right)",
            r"\hat{H} = \hbar\omega\!\left(\hat{a}^\dagger\hat{a} + \tfrac{1}{2}\right)",
        ],
        intuition="The harmonic oscillator is the most important quantum system — it appears in every quantum field theory. Remarkably, the algebra of raising/lowering operators solves it without ever writing down the wavefunction.",
        book_refs=["griffiths", "shankar", "sakurai", "cohen-tannoudji"],
        problem_ids=[],  # derived from problems.py at serialization,
    ),
    Topic(
        id="operators-observables",
        title="Operators and Observables",
        level="intermediate",
        prerequisites=["wavefunction-born-rule", "schrodinger-equation"],
        key_concepts=["Hermitian operators", "eigenvalues and eigenstates", "expectation values", "spectrum of observables"],
        key_equations=[r"\langle A \rangle = \langle\psi|\hat{A}|\psi\rangle", r"\hat{A}|\phi_n\rangle = a_n|\phi_n\rangle"],
        intuition="In QM every measurable quantity is represented by a Hermitian operator. Measuring it gives one of its eigenvalues, and the state 'collapses' to the corresponding eigenstate. The expectation value is the average over many measurements.",
        book_refs=["griffiths", "shankar", "dirac", "sakurai"],
        problem_ids=[],  # derived from problems.py at serialization,
    ),
    Topic(
        id="commutators",
        title="Commutators and Compatible Observables",
        level="intermediate",
        prerequisites=["operators-observables"],
        key_concepts=["commutator [A,B]=AB-BA", "canonical commutation relation [x,p]=iℏ", "commutator of position and momentum operators", "simultaneous eigenstates iff [A,B]=0", "generalized uncertainty principle"],
        key_equations=[r"[\hat{x},\hat{p}] = i\hbar", r"\Delta A\,\Delta B \geq \tfrac{1}{2}|{\langle[\hat{A},\hat{B}]\rangle}|"],
        intuition="Two operators commute iff they can be simultaneously measured precisely. Position and momentum famously do NOT commute — this is the algebraic root of the uncertainty principle, not just a measurement disturbance story.",
        book_refs=["griffiths", "shankar", "sakurai"],
        problem_ids=[],  # derived from problems.py at serialization,
    ),
    Topic(
        id="ehrenfest-correspondence-principle",
        title="Ehrenfest's Theorem and the Correspondence Principle",
        level="intermediate",
        prerequisites=["schrodinger-equation", "operators-observables", "lagrangian-hamiltonian-mechanics"],
        key_concepts=["Ehrenfest's theorem", "expectation values obeying Newton's laws", "the correspondence principle", "recovering classical physics as a limit", "large quantum number limit"],
        key_equations=[r"\frac{d}{dt}\langle \hat{x} \rangle = \frac{\langle \hat{p} \rangle}{m}", r"\frac{d}{dt}\langle \hat{A} \rangle = \frac{1}{i\hbar}\langle [\hat{A}, \hat{H}] \rangle"],
        intuition="Ehrenfest's theorem says expectation values of position and momentum obey Newton's second law almost exactly — swap operators for expectation values in the commutator with the Hamiltonian and classical mechanics falls straight out. This is the precise, quantitative version of Bohr's correspondence principle: quantum predictions must reduce to classical ones wherever classical mechanics is known to work well, typically for large quantum numbers or macroscopic scales.",
        book_refs=[],
        problem_ids=[],
    ),
    Topic(
        id="schrodinger-heisenberg-pictures",
        title="The Schrödinger and Heisenberg Pictures",
        level="intermediate",
        prerequisites=["schrodinger-equation", "operators-observables"],
        key_concepts=["Schrodinger picture: states evolve, operators fixed", "Heisenberg picture: operators evolve, states fixed", "Heisenberg equation of motion", "unitary time-evolution operator", "both pictures give identical physical predictions"],
        key_equations=[r"i\hbar \frac{\partial}{\partial t}|\psi(t)\rangle = \hat{H}|\psi(t)\rangle", r"\frac{d\hat{A}_H}{dt} = \frac{1}{i\hbar}[\hat{A}_H, \hat{H}]"],
        intuition="Both pictures compute the same measurable predictions — they only disagree about where to put the time dependence. In the Schrodinger picture (the default everywhere else in this curriculum), the wavefunction evolves while operators like x and p stay fixed. In the Heisenberg picture, states are frozen and the operators evolve instead, via an equation that echoes the classical equation of motion with the commutator standing in for the Poisson bracket — the same structural link to classical mechanics that shows up in Ehrenfest's theorem.",
        book_refs=[],
        problem_ids=[],
    ),
    Topic(
        id="dirac-notation",
        title="Dirac Notation & Hilbert Space",
        level="intermediate",
        prerequisites=["operators-observables", "wavefunction-born-rule"],
        key_concepts=["kets |ψ⟩ and bras ⟨ψ|", "inner product ⟨φ|ψ⟩", "completeness relation", "representation in different bases"],
        key_equations=[r"\langle x|\psi\rangle = \psi(x)", r"\sum_n |n\rangle\langle n| = \hat{I}"],
        intuition="Dirac notation is a powerful shorthand that separates physics from any particular representation. A state vector |ψ⟩ exists independently of whether we write it as a wavefunction or a spin vector.",
        book_refs=["shankar", "dirac", "sakurai", "townsend"],
        problem_ids=[],
    ),
    Topic(
        id="measurement-postulates",
        title="Postulates of Quantum Mechanics",
        level="intermediate",
        prerequisites=["dirac-notation", "operators-observables", "wavefunction-born-rule"],
        key_concepts=["state vector postulate", "observable postulate", "measurement postulate (projection)", "time evolution postulate", "Born rule", "wavefunction collapse upon measurement"],
        key_equations=[r"P(a_n) = |\langle a_n|\psi\rangle|^2", r"|\psi\rangle \xrightarrow{\text{measure}} |a_n\rangle"],
        intuition="QM has a small set of axioms: (1) state is a vector; (2) observables are Hermitian operators; (3) measurement gives an eigenvalue with probability = squared amplitude; (4) between measurements, Schrödinger evolves the state.",
        book_refs=["shankar", "dirac", "ballentine", "weinberg-qm"],
        problem_ids=[],
    ),
    Topic(
        id="hydrogen-atom",
        title="The Hydrogen Atom",
        level="intermediate",
        prerequisites=["schrodinger-equation", "operators-observables", "bohr-model"],
        key_concepts=["3D Schrödinger equation in spherical coordinates", "quantum numbers n, l, m", "orbital shapes", "exact energy spectrum"],
        key_equations=[
            r"E_n = -\frac{13.6\,\text{eV}}{n^2}",
            r"\psi_{nlm}(r,\theta,\phi) = R_{nl}(r)Y_l^m(\theta,\phi)",
        ],
        intuition="Solving Schrödinger's equation for the Coulomb potential gives the exact hydrogen spectrum — a triumph of QM. Three quantum numbers (n, l, m) emerge naturally from the boundary conditions in 3D.",
        book_refs=["griffiths", "shankar", "cohen-tannoudji", "zettili"],
        problem_ids=[],  # derived from problems.py at serialization,
    ),
    # ─── ADVANCED ─────────────────────────────────────────────────────────────
    Topic(
        id="spin-pauli",
        title="Spin and Pauli Matrices",
        level="advanced",
        prerequisites=["operators-observables", "commutators", "dirac-notation"],
        key_concepts=["intrinsic angular momentum", "spin-½", "Pauli matrices σₓ σᵧ σᵤ", "Stern-Gerlach experiment", "spinors"],
        key_equations=[
            r"S_z|\pm\rangle = \pm\frac{\hbar}{2}|\pm\rangle",
            r"\boldsymbol{\sigma}_x = \begin{pmatrix}0&1\\1&0\end{pmatrix},\quad \boldsymbol{\sigma}_z = \begin{pmatrix}1&0\\0&-1\end{pmatrix}",
        ],
        intuition="Electrons have an intrinsic angular momentum called spin that has no classical analogue. A spin-½ particle in a magnetic field can only be 'up' or 'down'. Pauli matrices encode the algebra of spin and underpin all of quantum information.",
        book_refs=["sakurai", "townsend", "griffiths", "cohen-tannoudji"],
        problem_ids=[],  # derived from problems.py at serialization,
    ),
    Topic(
        id="angular-momentum-addition",
        title="Addition of Angular Momentum & Clebsch–Gordan",
        level="advanced",
        prerequisites=["spin-pauli", "hydrogen-atom"],
        key_concepts=["total angular momentum J = L + S", "Clebsch–Gordan coefficients", "triplet and singlet states", "j = |l-s| to l+s"],
        key_equations=[r"|j_1 j_2; j m\rangle = \sum_{m_1 m_2} C^{jm}_{j_1 m_1 j_2 m_2}|j_1 m_1\rangle|j_2 m_2\rangle"],
        intuition="When two angular momenta couple, the total can range from |j₁-j₂| to j₁+j₂. The Clebsch–Gordan coefficients tell you the overlap between the coupled and uncoupled bases — they appear throughout atomic, nuclear, and particle physics.",
        book_refs=["sakurai", "cohen-tannoudji", "griffiths"],
        problem_ids=[],
    ),
    Topic(
        id="time-independent-perturbation",
        title="Time-Independent Perturbation Theory",
        level="advanced",
        prerequisites=["operators-observables", "hydrogen-atom", "spin-pauli"],
        key_concepts=["small perturbation H'", "first and second order energy corrections", "first order state corrections", "degenerate perturbation theory"],
        key_equations=[
            r"E_n^{(1)} = \langle n^{(0)}|H'|n^{(0)}\rangle",
            r"E_n^{(2)} = \sum_{m\neq n}\frac{|\langle m|H'|n\rangle|^2}{E_n^{(0)}-E_m^{(0)}}",
        ],
        intuition="Most quantum systems can't be solved exactly. If H = H₀ + λH' with λ small, we can expand in powers of λ. First-order corrections involve only the expectation value of the perturbation in the unperturbed state.",
        book_refs=["griffiths", "shankar", "sakurai", "cohen-tannoudji"],
        problem_ids=[],  # derived from problems.py at serialization,
    ),
    Topic(
        id="time-dependent-perturbation",
        title="Time-Dependent Perturbation Theory",
        level="advanced",
        prerequisites=["time-independent-perturbation", "measurement-postulates"],
        key_concepts=["Fermi's golden rule", "transition rate", "selection rules", "absorption and stimulated emission"],
        key_equations=[
            r"\Gamma_{i\to f} = \frac{2\pi}{\hbar}|\langle f|H'|i\rangle|^2\rho(E_f)",
        ],
        intuition="When a perturbation oscillates at just the right frequency, it drives transitions between energy levels. Fermi's golden rule gives the transition rate — the foundation of spectroscopy, laser physics, and quantum optics.",
        book_refs=["griffiths", "sakurai", "cohen-tannoudji"],
        problem_ids=[],
    ),
    Topic(
        id="variational-method",
        title="The Variational Method",
        level="advanced",
        prerequisites=["time-independent-perturbation", "operators-observables"],
        key_concepts=["variational principle", "trial wavefunction", "upper bound on ground state energy", "Hartree-Fock method"],
        key_equations=[r"E_{\text{gs}} \leq \frac{\langle\psi_T|\hat{H}|\psi_T\rangle}{\langle\psi_T|\psi_T\rangle}"],
        intuition="For any trial wavefunction, the expectation value of H is always ≥ the true ground state energy. So we can find approximate ground states by minimizing over a family of trial functions — the basis of all quantum chemistry calculations.",
        book_refs=["griffiths", "shankar", "cohen-tannoudji"],
        problem_ids=[],
    ),
    Topic(
        id="wkb",
        title="WKB Approximation",
        level="advanced",
        prerequisites=["step-barrier-tunneling", "schrodinger-equation"],
        key_concepts=["semiclassical limit", "slowly varying potential", "connection formulas", "tunneling rate", "Bohr-Sommerfeld quantization"],
        key_equations=[
            r"\psi(x) \approx \frac{A}{\sqrt{p(x)}}e^{\pm i\int p(x')\,dx'/\hbar}",
            r"\oint p\,dq = \left(n+\tfrac{1}{2}\right)h",
        ],
        intuition="When the potential varies slowly compared to the de Broglie wavelength, the wavefunction locally looks like a plane wave with a position-dependent wavelength. This semiclassical approximation is exact in the ℏ→0 limit.",
        book_refs=["griffiths", "landau-lifshitz-qm"],
        problem_ids=[],
    ),
    Topic(
        id="identical-particles",
        title="Identical Particles & Symmetrization",
        level="advanced",
        prerequisites=["measurement-postulates", "spin-pauli", "wavefunction-born-rule"],
        key_concepts=["indistinguishable particles", "exchange symmetry", "bosons (symmetric) vs fermions (antisymmetric)", "Pauli exclusion principle", "Slater determinant"],
        key_equations=[
            r"\psi(1,2) = \begin{cases} +\psi(2,1) & \text{bosons} \\ -\psi(2,1) & \text{fermions}\end{cases}",
        ],
        intuition="In QM, identical particles literally have no identity — swapping two electrons gives the same physical state. Fermions (half-integer spin) are antisymmetric under exchange, giving the Pauli exclusion principle that underlies the entire periodic table.",
        book_refs=["griffiths", "sakurai", "cohen-tannoudji", "ballentine"],
        problem_ids=[],
    ),
    Topic(
        id="scattering-theory",
        title="Scattering Theory",
        level="advanced",
        prerequisites=["step-barrier-tunneling", "time-independent-perturbation"],
        key_concepts=["cross section", "Born approximation", "partial waves", "S-matrix", "optical theorem"],
        key_equations=[
            r"\frac{d\sigma}{d\Omega} = |f(\theta)|^2",
            r"f(\theta) \approx -\frac{m}{2\pi\hbar^2}\int e^{i(\mathbf{k}-\mathbf{k}')\cdot\mathbf{r}}V(\mathbf{r})\,d^3r",
        ],
        intuition="Scattering experiments are how we probe quantum systems. The differential cross section |f(θ)|² tells us how particles scatter at each angle. Born approximation works when the potential is weak compared to the incident energy.",
        book_refs=["sakurai", "griffiths", "landau-lifshitz-qm"],
        problem_ids=[],
    ),
    # ─── ADVANCED TOPICS ──────────────────────────────────────────────────────
    Topic(
        id="path-integrals",
        title="Feynman Path Integrals",
        level="advanced_topics",
        prerequisites=["schrodinger-equation", "wkb", "time-dependent-perturbation"],
        key_concepts=["sum over all paths", "action S[x(t)]", "stationary phase = classical path", "propagator", "equivalent to Schrödinger equation"],
        key_equations=[
            r"\langle x_f,t_f|x_i,t_i\rangle = \int \mathcal{D}[x(t)]\,e^{iS[x(t)]/\hbar}",
        ],
        intuition="Feynman's formulation: a quantum particle explores ALL possible paths simultaneously. Each path contributes with amplitude exp(iS/ℏ). Paths near the classical action interfere constructively; wild paths cancel. In the classical limit, only the stationary-action path survives.",
        book_refs=["feynman-hibbs", "sakurai"],
        problem_ids=[],
    ),
    Topic(
        id="relativistic-qm",
        title="Relativistic Quantum Mechanics & the Dirac Equation",
        level="advanced_topics",
        prerequisites=["spin-pauli", "schrodinger-equation"],
        key_concepts=["Dirac equation", "spinors", "antiparticles (positrons)", "fine structure", "Klein-Gordon equation"],
        key_equations=[
            r"(i\gamma^\mu\partial_\mu - mc)\psi = 0",
            r"\gamma^\mu = (\beta, \beta\boldsymbol{\alpha})",
        ],
        intuition="Combining special relativity with QM forced Dirac to write a first-order equation for spin-½ particles. It automatically predicted spin, correctly computed the electron's magnetic moment, and predicted antimatter — one of the greatest achievements in theoretical physics.",
        book_refs=["dirac", "sakurai"],
        problem_ids=[],
    ),
    Topic(
        id="second-quantization",
        title="Second Quantization & QFT Introduction",
        level="advanced_topics",
        prerequisites=["identical-particles", "harmonic-oscillator", "relativistic-qm"],
        key_concepts=["field operators", "creation and annihilation operators for fields", "Fock space", "quantization of EM field", "photons as quanta"],
        key_equations=[
            r"[\hat{a}_k, \hat{a}_{k'}^\dagger] = \delta_{kk'}",
            r"\hat{\phi}(x) = \int \frac{d^3k}{(2\pi)^3}\frac{1}{\sqrt{2\omega_k}}\left(\hat{a}_k e^{ikx} + \hat{a}_k^\dagger e^{-ikx}\right)",
        ],
        intuition="The harmonic oscillator's ladder operators generalize to fields. Instead of one oscillator with levels n=0,1,2,..., you get an oscillator for each mode, and each excitation is a particle. This is the mathematical language of the Standard Model.",
        book_refs=["sakurai", "weinberg-qm"],
        problem_ids=[],
    ),
    Topic(
        id="quantum-information",
        title="Quantum Information & Computing",
        level="advanced_topics",
        prerequisites=["spin-pauli", "measurement-postulates", "identical-particles"],
        key_concepts=["qubits", "quantum gates", "entanglement as resource", "no-cloning theorem", "quantum error correction", "Grover's and Shor's algorithms", "qubit vs classical bit", "Bloch sphere representation", "Hadamard gate", "superposition and quantum parallelism", "tensor product of two-qubit basis states", "combining independent quantum systems", "Bell states"],
        key_equations=[
            r"|0\rangle = \begin{pmatrix}1\\0\end{pmatrix},\quad |1\rangle = \begin{pmatrix}0\\1\end{pmatrix}",
            r"H|0\rangle = \frac{1}{\sqrt{2}}(|0\rangle + |1\rangle)",
            r"|q_1\rangle \otimes |q_2\rangle = |q_1 q_2\rangle",
        ],
        intuition="A qubit is a quantum two-level system. Unlike a classical bit, it can be in a superposition. Entangled qubits exhibit correlations with no classical explanation. Quantum algorithms exploit interference to solve problems faster than any classical computer.",
        book_refs=["nielsen-chuang"],
        problem_ids=[],  # derived from problems.py at serialization,
    ),
    Topic(
        id="decoherence",
        title="Decoherence & Open Quantum Systems",
        level="advanced_topics",
        prerequisites=["measurement-postulates", "identical-particles"],
        key_concepts=["entanglement with environment", "density matrix", "Lindblad equation", "pointer states", "emergence of classicality"],
        key_equations=[
            r"\rho = \sum_k p_k |\psi_k\rangle\langle\psi_k|",
            r"\dot{\rho} = -\frac{i}{\hbar}[H,\rho] + \sum_k\!\left(L_k\rho L_k^\dagger - \tfrac{1}{2}L_k^\dagger L_k\rho - \tfrac{1}{2}\rho L_k^\dagger L_k\right)",
        ],
        intuition="Quantum systems don't live in isolation. When a quantum system entangles with its environment, superpositions appear to 'collapse' from our local perspective — without any mysterious wavefunction collapse. Decoherence explains why we never see cats in superpositions.",
        book_refs=["ballentine", "weinberg-qm", "nielsen-chuang"],
        problem_ids=[],
    ),
    Topic(
        id="quantum-optics",
        title="Quantum Optics",
        level="advanced_topics",
        prerequisites=["second-quantization", "time-dependent-perturbation"],
        key_concepts=["coherent states", "squeezed states", "photon statistics", "cavity QED", "Jaynes-Cummings model"],
        key_equations=[
            r"\hat{a}|\alpha\rangle = \alpha|\alpha\rangle\quad(\text{coherent state})",
            r"g^{(2)}(\tau) = \frac{\langle \hat{a}^\dagger\hat{a}^\dagger\hat{a}\hat{a}\rangle}{\langle\hat{a}^\dagger\hat{a}\rangle^2}",
        ],
        intuition="Quantum optics studies light at the single-photon level. Coherent states (laser light) are the most 'classical' quantum states. Squeezed states have noise below the vacuum level in one quadrature — used in gravitational wave detectors (LIGO).",
        book_refs=["cohen-tannoudji", "sakurai"],
        problem_ids=[],
    ),

    # ── quantum statistical mechanics ──────────────────────────────────────
    # Another hole found the same way as the relativity one: a question about
    # the connection between quantum and statistical mechanics matched
    # Postulates, WKB and Stellar Astrophysics, because the graph contained no
    # ensemble, partition function, entropy or mixed-state topic at all.
    Topic(
        id="density-matrix",
        title="Density Matrix & Mixed States",
        level="intermediate",
        prerequisites=["measurement-postulates", "dirac-notation"],
        key_concepts=["pure vs mixed states", "density operator", "partial trace",
                      "reduced density matrix", "purity", "von Neumann entropy",
                      "classical vs quantum uncertainty"],
        key_equations=[
            r"\hat{\rho} = \sum_i p_i |\psi_i\rangle\langle\psi_i|",
            r"\langle A \rangle = \mathrm{Tr}(\hat{\rho}\hat{A})",
            r"S = -k_B\,\mathrm{Tr}(\hat{\rho}\ln\hat{\rho})",
        ],
        intuition="A ket describes a system you know completely. The moment you are ignorant of which state was prepared — or you trace out a subsystem you cannot see — a single ket cannot represent it and you need the density matrix. This is the object where quantum uncertainty and ordinary statistical ignorance sit side by side, and it is the bridge to statistical mechanics.",
        book_refs=["sakurai", "ballentine", "cohen-tannoudji"],
        problem_ids=[],
    ),
    Topic(
        id="quantum-statistical-mechanics",
        title="Quantum Statistical Mechanics: Ensembles & Partition Functions",
        level="advanced",
        prerequisites=["density-matrix", "identical-particles"],
        key_concepts=["microcanonical, canonical and grand canonical ensembles",
                      "partition function", "Boltzmann factor", "thermal density matrix",
                      "free energy", "equipartition", "thermodynamic limit",
                      "statistical entropy"],
        key_equations=[
            r"Z = \mathrm{Tr}\left(e^{-\beta \hat{H}}\right),\quad \beta = \frac{1}{k_B T}",
            r"\hat{\rho}_{\text{thermal}} = \frac{e^{-\beta\hat{H}}}{Z}",
            r"F = -k_B T \ln Z",
        ],
        intuition="Statistical mechanics is what you do when you know the Hamiltonian but not the microstate. Put the system in contact with a heat bath and the density matrix becomes exp(-βH)/Z — every quantum energy level weighted by its Boltzmann factor. Thermodynamics then falls out of one function, the partition function.",
        book_refs=["landau-lifshitz-qm", "sakurai"],
        problem_ids=[],
    ),
    Topic(
        id="quantum-statistics",
        title="Bose–Einstein & Fermi–Dirac Statistics",
        level="advanced",
        prerequisites=["quantum-statistical-mechanics", "identical-particles"],
        key_concepts=["indistinguishability and counting", "Bose-Einstein distribution",
                      "Fermi-Dirac distribution", "Fermi energy", "degeneracy pressure",
                      "Bose-Einstein condensation", "chemical potential",
                      "classical limit"],
        key_equations=[
            r"\bar{n}_{\text{BE}} = \frac{1}{e^{\beta(\epsilon-\mu)} - 1}",
            r"\bar{n}_{\text{FD}} = \frac{1}{e^{\beta(\epsilon-\mu)} + 1}",
            r"E_F = \frac{\hbar^2}{2m}\left(3\pi^2 n\right)^{2/3}",
        ],
        intuition="Because identical particles cannot be labelled, counting states changes — and that alone splits matter in two. Bosons pile into the same state and can condense; fermions refuse, which is why atoms have structure and why a white dwarf resists gravity. Both distributions collapse to Boltzmann's when occupancy is low.",
        book_refs=["landau-lifshitz-qm", "griffiths", "sakurai"],
        problem_ids=[],
    ),

    # ── relativity, particles and cosmology ────────────────────────────────
    # The original 32 topics were a quantum-mechanics curriculum, so a question
    # spanning "quarks to quasars" matched the Dirac equation and nothing else:
    # searching the graph for cosmology, quasar or quark returned nothing, and
    # gravitation matched only Quantum Optics. The Physics shelf already holds
    # relativity, particle-physics and astrophysics books — these topics give
    # the matcher something to attach them to.
    Topic(
        id="special-relativity",
        title="Special Relativity",
        level="basics",
        prerequisites=[],
        key_concepts=["postulates of relativity", "time dilation", "length contraction",
                      "Lorentz transformation", "spacetime interval", "mass-energy equivalence",
                      "four-vectors", "relativistic momentum"],
        key_equations=[
            r"\gamma = \frac{1}{\sqrt{1 - v^2/c^2}}",
            r"E^2 = (pc)^2 + (mc^2)^2",
            r"\Delta s^2 = c^2\Delta t^2 - \Delta x^2 - \Delta y^2 - \Delta z^2",
        ],
        intuition="Demand that the speed of light is the same for everyone and geometry has to give way: clocks run slow, lengths contract, and simultaneity stops being absolute. What survives is the spacetime interval, the quantity all observers agree on.",
        book_refs=["landau-lifshitz-qm"],
        problem_ids=[],
    ),
    Topic(
        id="general-relativity",
        title="General Relativity & Curved Spacetime",
        level="advanced",
        prerequisites=["special-relativity"],
        key_concepts=["equivalence principle", "spacetime curvature", "metric tensor",
                      "geodesics", "Einstein field equations", "gravitational time dilation",
                      "black holes", "event horizon", "gravitational waves"],
        key_equations=[
            r"G_{\mu\nu} + \Lambda g_{\mu\nu} = \frac{8\pi G}{c^4} T_{\mu\nu}",
            r"ds^2 = -\left(1 - \frac{2GM}{rc^2}\right)c^2 dt^2 + \left(1 - \frac{2GM}{rc^2}\right)^{-1} dr^2 + r^2 d\Omega^2",
            r"r_s = \frac{2GM}{c^2}",
        ],
        intuition="Gravity is not a force but the shape of spacetime. Free-falling bodies travel the straightest available paths through a geometry that mass and energy themselves bend — matter tells spacetime how to curve, curvature tells matter how to move.",
        book_refs=["landau-lifshitz-qm"],
        problem_ids=[],
    ),
    Topic(
        id="standard-model",
        title="The Standard Model: Quarks, Leptons & Forces",
        level="advanced_topics",
        prerequisites=["relativistic-qm", "second-quantization"],
        key_concepts=["quarks", "leptons", "gauge bosons", "colour charge", "quantum chromodynamics",
                      "electroweak unification", "Higgs mechanism", "confinement", "hadrons",
                      "flavour", "generations"],
        key_equations=[
            r"SU(3)_C \times SU(2)_L \times U(1)_Y",
            r"\mathcal{L}_{\text{QED}} = \bar{\psi}(i\gamma^\mu D_\mu - m)\psi - \tfrac{1}{4}F_{\mu\nu}F^{\mu\nu}",
        ],
        intuition="Every particle we have found is either a matter fermion (six quarks, six leptons) or a force carrier, and the forces themselves come from demanding local gauge symmetry. Quarks never appear alone — pull two apart and the colour field makes new ones rather than let a bare colour charge exist.",
        book_refs=["sakurai", "weinberg-qm"],
        problem_ids=[],
    ),
    Topic(
        id="qft-fundamentals",
        title="Quantum Field Theory: Fields, Feynman Diagrams & Renormalisation",
        level="advanced_topics",
        prerequisites=["second-quantization", "relativistic-qm"],
        key_concepts=["fields as fundamental", "particle creation and annihilation",
                      "Feynman diagrams", "propagators", "virtual particles", "loop corrections",
                      "renormalisation", "running coupling", "vacuum energy"],
        key_equations=[
            r"\mathcal{L} = \tfrac{1}{2}(\partial_\mu\phi)^2 - \tfrac{1}{2}m^2\phi^2 - \tfrac{\lambda}{4!}\phi^4",
            r"\langle 0 | T\{\phi(x)\phi(y)\} | 0 \rangle = \int\!\frac{d^4k}{(2\pi)^4}\frac{i e^{-ik(x-y)}}{k^2 - m^2 + i\epsilon}",
        ],
        intuition="Marry special relativity to quantum mechanics and particle number stops being fixed — energy can always make new particles. The field, not the particle, becomes the basic object, and particles are its excitations.",
        book_refs=["weinberg-qm", "sakurai", "feynman-hibbs"],
        problem_ids=[],
    ),
    Topic(
        id="astrophysics-stars",
        title="Stellar Astrophysics & Compact Objects",
        level="advanced",
        prerequisites=["identical-particles", "special-relativity"],
        key_concepts=["hydrostatic equilibrium", "nuclear fusion", "stellar evolution",
                      "electron degeneracy pressure", "Chandrasekhar limit", "white dwarfs",
                      "neutron stars", "supernovae", "accretion discs", "quasars"],
        key_equations=[
            r"M_{\text{Ch}} \approx 1.4\, M_\odot",
            r"\frac{dP}{dr} = -\frac{G M(r)\rho(r)}{r^2}",
            r"L_{\text{Edd}} = \frac{4\pi G M m_p c}{\sigma_T}",
        ],
        intuition="A star is a slow argument between gravity pulling in and pressure pushing out. When fusion stops, the outcome is decided by quantum mechanics: electron degeneracy holds up a white dwarf until 1.4 solar masses, beyond which nothing stops the collapse. Quasars are the light of matter falling onto the black holes that result.",
        book_refs=["landau-lifshitz-qm"],
        problem_ids=[],
    ),
    Topic(
        id="cosmology",
        title="Cosmology: The Expanding Universe",
        level="advanced_topics",
        prerequisites=["general-relativity", "standard-model"],
        key_concepts=["Hubble expansion", "FLRW metric", "cosmic microwave background",
                      "Big Bang nucleosynthesis", "dark matter", "dark energy", "inflation",
                      "redshift", "critical density"],
        key_equations=[
            r"H^2 = \left(\frac{\dot{a}}{a}\right)^2 = \frac{8\pi G}{3}\rho - \frac{kc^2}{a^2} + \frac{\Lambda c^2}{3}",
            r"1 + z = \frac{a(t_0)}{a(t_{\text{emit}})}",
        ],
        intuition="Apply general relativity to everything at once and the universe cannot sit still — it expands. Run the expansion backwards and you get a hot dense beginning whose afterglow we still measure, and whose light-element abundances match the prediction.",
        book_refs=["landau-lifshitz-qm"],
        problem_ids=[],
    ),
]}


def topic(topic_id: str) -> Topic:
    """Return a Topic by ID, raising KeyError if not found."""
    try:
        return TOPICS[topic_id]
    except KeyError:
        raise KeyError(f"Unknown topic id: {topic_id!r}. Available: {sorted(TOPICS)}")


def topics_at_level(level: str) -> List[Topic]:
    """Return all topics at a given level, in curriculum order."""
    order = {
        "basics": ["wave-particle-duality", "photoelectric-effect", "de-broglie", "double-slit",
                   "blackbody-radiation", "bohr-model", "uncertainty-principle", "wavefunction-born-rule",
                   "schrodinger-equation", "particle-in-a-box"],
        "intermediate": ["step-barrier-tunneling", "finite-well", "harmonic-oscillator",
                         "operators-observables", "commutators", "dirac-notation",
                         "measurement-postulates", "hydrogen-atom"],
        "advanced": ["spin-pauli", "angular-momentum-addition", "time-independent-perturbation",
                     "time-dependent-perturbation", "variational-method", "wkb",
                     "identical-particles", "scattering-theory"],
        "advanced_topics": ["path-integrals", "relativistic-qm", "second-quantization",
                            "quantum-information", "decoherence", "quantum-optics"],
    }
    ids = order.get(level, [])
    return [TOPICS[tid] for tid in ids if tid in TOPICS]


def books_at_level(level: str) -> List[Book]:
    """Return books aimed at a given level."""
    return [b for b in BOOKS.values() if b.level == level]


def books_for_topic(topic_id: str) -> List[Book]:
    """Return books that cover a given topic."""
    t = TOPICS.get(topic_id)
    if not t:
        return []
    return [BOOKS[bid] for bid in t.book_refs if bid in BOOKS]


def learning_path(topic_id: str) -> List[str]:
    """Return prerequisite-ordered list of topic IDs ending at topic_id (DAG walk, cycle-safe)."""
    result: List[str] = []
    visited: set = set()
    visiting: set = set()

    def _visit(tid: str) -> None:
        if tid in visited or tid in visiting:
            return
        visiting.add(tid)
        t = TOPICS.get(tid)
        if t:
            for prereq in t.prerequisites:
                _visit(prereq)
        visiting.discard(tid)
        visited.add(tid)
        result.append(tid)

    _visit(topic_id)
    return result
